# As much as possible, this file should be kept in sync with:
# https://github.com/napari/napari/blob/main/.circleci/config.yaml
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.1/configuration-reference
version: 2.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects.
# See: https://circleci.com/docs/2.1/orb-intro/
jobs:
  preview-docs:
    docker:
      - image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            . /opt/conda/etc/profile.d/conda.sh
            conda env create -f .ci_scripts/environment.yml
            conda activate conda-forge-docs
            .ci_scripts/update_docs
      - store_artifacts:
          path: build/
      - persist_to_workspace:
          root: .
          paths:
            - build/
workflows:
  preview-docs:
    jobs:
      - preview-docs
