# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.1/configuration-reference
version: 2.1
jobs:
  preview-docs:
    docker:
      - image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            . /opt/conda/etc/profile.d/conda.sh
            set -x
            conda env create -f .ci_scripts/environment.yml
            conda info
            conda list conda-forge-docs
      - run:
          name: Build site
          command: |
            . /opt/conda/etc/profile.d/conda.sh
            conda activate conda-forge-docs
            set -x
            export DOCUSAURUS_URL="https://output.circle-artifacts.com/"
            export DOCUSAURUS_BASE_URL="/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/build/"
            .ci_scripts/update_docs
            # Known limitation in CircleCI: https://discuss.circleci.com/t/circle-artifacts-com-not-using-index-html/320/3
            # Post-process href's so "$DOCUSAURUS_BASE_URL/.*/.*/.../" becomes "$DOCUSAURUS_BASE_URL/.*/index.html"
            find build/ -type f -name "*.html" -exec sed -i -E "s|href=\"$DOCUSAURUS_BASE_URL([^\"]+/)\"|href=\"$DOCUSAURUS_BASE_URL\1index.html\"|g" {} \;
      - store_artifacts:
          path: build/
      - persist_to_workspace:
          root: .
          paths:
            - build/
workflows:
  preview-docs:
    jobs:
      - preview-docs
