# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.1/configuration-reference
version: 2.1
jobs:
  preview-docs:
    docker:
      - image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            . /opt/conda/etc/profile.d/conda.sh
            conda env create -f .ci_scripts/environment.yml
      - run:
          name: Build site
          command: |
            . /opt/conda/etc/profile.d/conda.sh
            conda activate conda-forge-docs
            export DOCUSAURUS_URL="https://output.circle-artifacts.com/"
            export DOCUSAURUS_BASE_URL="/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/build/"
            .ci_scripts/update_docs
      - store_artifacts:
          path: build/
      - persist_to_workspace:
          root: .
          paths:
            - build/
workflows:
  preview-docs:
    jobs:
      - preview-docs
